### ISSUE TITLE
Comparing with R3Live

### ISSUE THREAD

**Issue by Camilochiang** [hku-mars/FAST-LIVO#4]
When comparing the resolution of FAST-LIVO to R3live from your videos, is it clear for me that FAST-LIVO is doing a better work . Have been this difference been quantified?
**R3Live**
<img width="1440" alt="Skjermbilde 2022-05-01 kl  22 22 36" src="https://user-images.githubusercontent.com/48471579/166163406-0c174555-7395-4d5c-a556-ce9839621c47.png">
**FAST-LIVO***
<img width="1440" alt="Skjermbilde 2022-05-01 kl  22 25 13" src="https://user-images.githubusercontent.com/48471579/166163399-d522b082-f671-451a-bc93-375c71ae0faf.png">

**Comment by xuankuzcr** [comment]
Hi, Camilo
Thanks for your attention! First of all, we can't determine whose effect is better only from the performance of the two systems in this scenario. This is because the two bags come from different data acquisition devices, different lighting conditions, different acquisition routes and different camera parameters, which will have a huge impact on the final reconstruction results. Secondly,  we haven't compared the differences between them quantitatively, maybe we'll do this experiment later. However, maintaining high accuracy and robustness on the premise of high speed is what we claim in our system, which doesn't contradict R3LIVE. 
Actually, for this non-degenerate structured scenario, their accuracy should be similar, benefited from the high-precision odom provided with LIO subsystem (FAST-LIO2).

**Comment by Camilochiang** [comment]
Thanks for your answer!

**Comment by xuankuzcr** [comment]
[Here](https://www.bilibili.com/video/BV1oA41197fe/?spm_id_from=333.337.search-card.all.click) is someone who compared the colored point clouds with the same data, the same computer configuration and the same perspective. You can take a look and compare them qualitatively.

**Comment by FPSychotic** [comment]
I find here two observations, R3Live can rise the definition of the vertex colour, I can find on my hand held scanner both can get the same coloured quality.
I find R3live is more CPU power hungry in same quality range, but Fast LIVO will  end with 16Gb RAM in 3 min, R3 Live can keep working for at least 15mim.
For other side there is not a real or practical utility that the point cloud could or not be more defined in n colour , as the map in realtime cannot be saved.
It looks the R3live VIO subsystem is less dependent of the frame rate, camera quality or global shutter or not, fastlivo does, so with my d435 looks R3Live gives better tracking in indoors and low textured areas, didn't test in outdoors. 
This is what I find, but other hardware, computer, setups could give different result in a way or other

**Comment by FPSychotic** [comment]
Just let know and longer test fast-livo has effectively better definition in the coloured pointcloud. And it is more solid VO tracking. Is quite nice, but cannot save the map directly and the ram it eats make it difficult to work in realtime. But I think the Dev is brilliant and the software does what he wanted, is better that I said in my first comment based in indoor tests
