### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by Camilochiang** [hku-mars/FAST-LIVO#8]
@xuankuzcr Are you still alive? Do you have any idea when you planning to release the code?

Thanks!

**Comment by fanfanrealikun** [comment]
Alive? How dare you say that? Just like a parasite that lives on open source code. Are you in such a hurry because you're going to die tonight?

![image](https://user-images.githubusercontent.com/113509848/190108001-e8267daf-5eb9-4bd8-9200-2c6538039ea3.png)

By the way, thanks for your great work, @xuankuzcr. Don't care about rude people on the Internet, and be yourself. I look forward to seeing more great works from you and your lab.
